name: "Get Image Tag"
description: "Generates a tag for Docker image"

inputs:
  branch_name:
    description: 'Name of the branch the workflow runs on'
    required: true

runs:
  using: "composite"
  steps:
    - name: Get docker image tag name
      shell: bash
      env:
        BRANCH_NAME: ${{ inputs.branch_name }}
        RUN_ID: ${{ github.run_id }}
      run: |
        if [[ "$BRANCH_NAME" == "master" ]] || [[ "$BRANCH_NAME" == release/* ]]; then
          TAG_VERSION="$(jq -cr '.version' < package.json)"
        else
          TAG_VERSION="${BRANCH_NAME}-${RUN_ID}"
        fi
        echo "TAG_VERSION=$TAG_VERSION" >> $GITHUB_ENV
